#!/usr/bin/env node
/**
 * Generates src/shared/theme/generated.ts from design/tokens/.
 * Run: npm run build:theme
 */
import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const tokensPath = join(root, 'design/tokens/tokens.json');
const materialPath = join(root, 'design/tokens/material-theme.json');
const outPath = join(root, 'src/shared/theme/generated.ts');

function readJson(path) {
  return JSON.parse(readFileSync(path, 'utf8'));
}

/** DTCG token leaf: { $value, $type } or nested groups */
function resolveValue(node) {
  if (node == null || typeof node !== 'object') return node;
  if ('$value' in node) return node.$value;
  const out = {};
  for (const [key, val] of Object.entries(node)) {
    if (key.startsWith('$')) continue;
    out[key] = resolveValue(val);
  }
  return out;
}

function resolveColorModes(colorGroup) {
  const resolved = resolveValue(colorGroup);
  const light = {};
  const dark = {};
  for (const [key, val] of Object.entries(resolved)) {
    if (val && typeof val === 'object' && 'light' in val && 'dark' in val) {
      light[key] = val.light;
      dark[key] = val.dark;
    }
  }
  return { light, dark };
}

function num(v) {
  return typeof v === 'string' ? Number.parseInt(v, 10) : v;
}

/** App spacing keys (legacy) → token keys in design/tokens/tokens.json */
const SPACING_LEGACY_MAP = {
  xs: 'xs',
  s: 'sm',
  m: 'lg',
  l: '2xl',
  xl: '3xl',
  xxl: '5xl',
};

const BORDER_RADIUS_LEGACY_MAP = {
  xs: 'xs',
  s: 'sm',
  m: 'md',
  l: 'lg',
  xl: 'xl',
  full: 'full',
};

function formatObject(obj, indent = 2) {
  const pad = ' '.repeat(indent);
  const lines = Object.entries(obj).map(([k, v]) => {
    const key = /^[a-zA-Z_][a-zA-Z0-9_]*$/.test(k) ? k : JSON.stringify(k);
    const val = typeof v === 'string' ? `'${v}'` : v;
    return `${pad}${key}: ${val},`;
  });
  return `{\n${lines.join('\n')}\n${' '.repeat(indent - 2)}}`;
}

function main() {
  const tokens = readJson(tokensPath);
  const material = readJson(materialPath);

  // Colors: material-theme.json has full M3 schemes (incl. surfaceTint)
  const lightScheme = material.schemes?.light ?? {};
  const darkScheme = material.schemes?.dark ?? {};

  const colorKeys = Object.keys(lightScheme).filter((k) => !k.includes('Fixed'));
  const lightColors = {};
  const darkColors = {};
  for (const key of colorKeys) {
    if (lightScheme[key] != null) lightColors[key] = lightScheme[key];
    if (darkScheme[key] != null) darkColors[key] = darkScheme[key];
  }

  // Fallback / cross-check from tokens.json color.* (light/dark modes)
  const fromTokens = resolveColorModes(tokens.color ?? {});
  for (const key of Object.keys(fromTokens.light)) {
    if (lightColors[key] === undefined) lightColors[key] = fromTokens.light[key];
    if (darkColors[key] === undefined) darkColors[key] = fromTokens.dark[key];
  }

  const spacingRaw = resolveValue(tokens.spacing ?? {});
  const spacing = {};
  for (const [legacy, tokenKey] of Object.entries(SPACING_LEGACY_MAP)) {
    spacing[legacy] = num(spacingRaw[tokenKey]);
  }

  const radiusRaw = resolveValue(tokens.borderRadius ?? {});
  const borderRadius = {};
  for (const [legacy, tokenKey] of Object.entries(BORDER_RADIUS_LEGACY_MAP)) {
    borderRadius[legacy] = num(radiusRaw[tokenKey]);
  }

  const fontSize = resolveValue(tokens.fontSize ?? {});
  const fontWeight = resolveValue(tokens.fontWeight ?? {});
  const lineHeight = resolveValue(tokens.lineHeight ?? {});

  const header = `// AUTO-GENERATED by scripts/build-theme.mjs — do not edit.
// Sources: design/tokens/material-theme.json (colors), design/tokens/tokens.json (spacing, radius, …)
// Regenerate: npm run build:theme
`;

  const body = `${header}
export const lightColors = ${formatObject(lightColors)} as const;

export const darkColors = ${formatObject(darkColors)} as const;

export const spacing = ${formatObject(spacing)} as const;

export const borderRadius = ${formatObject(borderRadius)} as const;

/** Raw token scales from tokens.json (DTCG names) */
export const fontSize = ${formatObject(Object.fromEntries(
    Object.entries(fontSize).map(([k, v]) => [k, num(v)]),
  ))} as const;

export const fontWeight = ${formatObject(fontWeight)} as const;

export const lineHeight = ${formatObject(lineHeight)} as const;
`;

  writeFileSync(outPath, body, 'utf8');
  console.log(`Wrote ${outPath}`);
  console.log(`  colors: ${colorKeys.length} roles × light/dark`);
  console.log(`  spacing: ${Object.keys(spacing).join(', ')}`);
}

main();
