// Auto-generated from config/material-theme.json (Material Theme Builder, seed #184FC5)
// Light and dark color schemes, typography scale, spacing

export const lightColors = {
  primary: '#4B5C92',
  surfaceTint: '#4B5C92',
  onPrimary: '#FFFFFF',
  primaryContainer: '#DBE1FF',
  onPrimaryContainer: '#334478',
  secondary: '#595E72',
  onSecondary: '#FFFFFF',
  secondaryContainer: '#DDE1F9',
  onSecondaryContainer: '#414659',
  tertiary: '#745470',
  onTertiary: '#FFFFFF',
  tertiaryContainer: '#FFD6F8',
  onTertiaryContainer: '#5B3D58',
  error: '#BA1A1A',
  onError: '#FFFFFF',
  errorContainer: '#FFDAD6',
  onErrorContainer: '#93000A',
  background: '#FAF8FF',
  onBackground: '#1A1B21',
  surface: '#FAF8FF',
  onSurface: '#1A1B21',
  surfaceVariant: '#E2E2EC',
  onSurfaceVariant: '#45464F',
  outline: '#757680',
  outlineVariant: '#C5C6D0',
  shadow: '#000000',
  scrim: '#000000',
  inverseSurface: '#2F3036',
  inverseOnSurface: '#F1F0F7',
  inversePrimary: '#B4C5FF',
  surfaceDim: '#DAD9E0',
  surfaceBright: '#FAF8FF',
  surfaceContainerLowest: '#FFFFFF',
  surfaceContainerLow: '#F4F3FA',
  surfaceContainer: '#EEEDF4',
  surfaceContainerHigh: '#E9E7EF',
  surfaceContainerHighest: '#E3E2E9',
} as const;

export const darkColors = {
  primary: '#B4C5FF',
  surfaceTint: '#B4C5FF',
  onPrimary: '#1B2D60',
  primaryContainer: '#334478',
  onPrimaryContainer: '#DBE1FF',
  secondary: '#C1C5DD',
  onSecondary: '#2B3042',
  secondaryContainer: '#414659',
  onSecondaryContainer: '#DDE1F9',
  tertiary: '#E2BBDB',
  onTertiary: '#422740',
  tertiaryContainer: '#5B3D58',
  onTertiaryContainer: '#FFD6F8',
  error: '#FFB4AB',
  onError: '#690005',
  errorContainer: '#93000A',
  onErrorContainer: '#FFDAD6',
  background: '#121318',
  onBackground: '#E3E2E9',
  surface: '#121318',
  onSurface: '#E3E2E9',
  surfaceVariant: '#45464F',
  onSurfaceVariant: '#C5C6D0',
  outline: '#8F909A',
  outlineVariant: '#45464F',
  shadow: '#000000',
  scrim: '#000000',
  inverseSurface: '#E3E2E9',
  inverseOnSurface: '#2F3036',
  inversePrimary: '#4B5C92',
  surfaceDim: '#121318',
  surfaceBright: '#38393F',
  surfaceContainerLowest: '#0D0E13',
  surfaceContainerLow: '#1A1B21',
  surfaceContainer: '#1E1F25',
  surfaceContainerHigh: '#292A2F',
  surfaceContainerHighest: '#34343A',
} as const;

export type ColorScheme = typeof lightColors;

export const spacing = {
  xs: 4,
  s: 8,
  m: 16,
  l: 24,
  xl: 32,
  xxl: 48,
} as const;

export const typography = {
  displayLarge:  { fontSize: 57, lineHeight: 64, fontWeight: '400' as const },
  displayMedium: { fontSize: 45, lineHeight: 52, fontWeight: '400' as const },
  displaySmall:  { fontSize: 36, lineHeight: 44, fontWeight: '400' as const },
  headlineLarge: { fontSize: 32, lineHeight: 40, fontWeight: '400' as const },
  headlineMedium:{ fontSize: 28, lineHeight: 36, fontWeight: '400' as const },
  headlineSmall: { fontSize: 24, lineHeight: 32, fontWeight: '400' as const },
  titleLarge:    { fontSize: 22, lineHeight: 28, fontWeight: '400' as const },
  titleMedium:   { fontSize: 16, lineHeight: 24, fontWeight: '500' as const },
  titleSmall:    { fontSize: 14, lineHeight: 20, fontWeight: '500' as const },
  bodyLarge:     { fontSize: 16, lineHeight: 24, fontWeight: '400' as const },
  bodyMedium:    { fontSize: 14, lineHeight: 20, fontWeight: '400' as const },
  bodySmall:     { fontSize: 12, lineHeight: 16, fontWeight: '400' as const },
  labelLarge:    { fontSize: 14, lineHeight: 20, fontWeight: '500' as const },
  labelMedium:   { fontSize: 12, lineHeight: 16, fontWeight: '500' as const },
  labelSmall:    { fontSize: 11, lineHeight: 16, fontWeight: '500' as const },
} as const;

export const borderRadius = {
  xs: 4,
  s:  8,
  m:  12,
  l:  16,
  xl: 28,
  full: 9999,
} as const;

export const theme = {
  light: lightColors,
  dark: darkColors,
  spacing,
  typography,
  borderRadius,
} as const;

export type Theme = typeof theme;
